project_id = "hrjaqfaqhclrmsfvxrxq"

[functions.generate-video]
verify_jwt = false

[functions.scrape-tiktok-products]
verify_jwt = false

[functions.scrape-tiktok-videos]
verify_jwt = false

[functions.transcribe-videos]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
